In [1]:
import torch
print(torch.__version__)

1.8.1+cu111


In [17]:
# Returns the default type of a tensor
torch.get_default_dtype()

torch.float16

In [16]:
# Cannot set cuda tensor types to default dtype
# torch.set_default_dtype(torch.cuda.FloatTensor)

# Sets the default tensor type
torch.set_default_dtype(torch.half)

In [20]:
# Create tensor from a given list
tensor = torch.Tensor([
    [1,2,3],
    [4,5,6]
])

In [21]:
# Checks variable is a tensor or not
torch.is_tensor(tensor)

True

In [22]:
# Returns number of elements
torch.numel(tensor)

6

In [23]:
# Create uninitialized tensor of a given size
torch.Tensor(2, 2)

tensor([[6.9336e-02, 9.8250e+01],
        [       nan, 0.0000e+00]])

In [24]:
# Creat tensor of a given size with random values
torch.rand(2, 3)

tensor([[0.6758, 0.4277, 0.3271],
        [0.5137, 0.2910, 0.4722]])

In [28]:
# Change the dtype of a tensor
torch.tensor([1,2,3]).type(torch.cuda.FloatTensor)

tensor([1., 2., 3.], device='cuda:0', dtype=torch.float32)

In [29]:
# Create a tensor of a given type
torch.cuda.DoubleTensor([1,2,3,4])

tensor([1., 2., 3., 4.], device='cuda:0', dtype=torch.float64)

In [35]:
# Create a tensor of the given size filled with 1
ones_tensor = torch.ones(2, 3)

In [36]:
# Create a tensor of size of the passed tensor filled with zeros
torch.zeros_like(ones_tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [37]:
# Create and fill tensor with fill  value
torch.full((2, 4), fill_value=5)

tensor([[5, 5, 5, 5],
        [5, 5, 5, 5]])

In [38]:
# Create 2d tensor of shape 5 x 5
# Ones are filled in the main diagonal
eye_tensor = torch.eye(5)
eye_tensor

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [39]:
# Returns the positions of non zero elements
torch.nonzero(eye_tensor)

tensor([[0, 0],
        [1, 1],
        [2, 2],
        [3, 3],
        [4, 4]])

In [ ]:
# Get 